### ISSUE TITLE
ext.cpp:16:10: fatal error: rice/Array.hpp: No such file or directory  #ruby version 2.5  #fasttext-0.1.3 #rice-4.0.4

### ISSUE THREAD

**Issue by iamsonivivek** [ankane/fastText-ruby#6]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.5.0/gems/fasttext-0.1.3/ext/fasttext
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.5.0 -r ./siteconf20230325-1-45luxh.rb extconf.rb
/bundle/ruby/2.5.0/gems/rice-4.0.4/lib/mkmf-rice.rb:16: warning: already initialized constant MakeMakefile::CONFTEST_C
/usr/local/lib/ruby/2.5.0/mkmf.rb:248: warning: previous definition of CONFTEST_C was here
checking for rice/rice.hpp in /bundle/ruby/2.5.0/gems/rice-4.0.4/include... yes
checking for -lstdc++... yes
creating Makefile

current directory: /bundle/ruby/2.5.0/gems/fasttext-0.1.3/ext/fasttext
make "DESTDIR=" clean

current directory: /bundle/ruby/2.5.0/gems/fasttext-0.1.3/ext/fasttext
make "DESTDIR="
compiling ext.cpp
cc1plus: warning: command line option ‘-Wimplicit-int’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++
ext.cpp:16:10: fatal error: rice/Array.hpp: No such file or directory
 #include <rice/Array.hpp>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:235: ext.o] Error 1

make failed, exit code 2

Gem files will remain installed in /bundle/ruby/2.5.0/gems/fasttext-0.1.3 for inspection.
Results logged to /bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/fasttext-0.1.3/gem_make.out

**Comment by ankane** [comment]
Hi @iamsonivivek, only the latest version is supported, and it requires Ruby 2.6+.
