### ISSUE TITLE
Unable to load fasttext 0.2.4 with ruby 3.0.1 in docker env

### ISSUE THREAD

**Issue by sandeepm96** [ankane/fastText-ruby#8]
Hey @ankane,

I am getting this error while building my project in docker env with ruby version 3.0.1p64.

```
bundler: failed to load command: thin (/project/vendor/bundle/ruby/3.0.1/ruby/3.0.0/bin/thin)
/project/vendor/bundle/ruby/3.0.1/ruby/3.0.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': /project/vendor/bundle/ruby/3.0.1/ruby/3.0.0/gems/fasttext-0.2.4/lib/fasttext/ext.so: undefined symbol: _ZTINSt10filesystem7__cxx1116filesystem_errorE - /project/vendor/bundle/ruby/3.0.1/ruby/3.0.0/gems/fasttext-0.2.4/lib/fasttext/ext.so (LoadError)
```

Upon researching a bit about `_ZTINSt10filesystem7__cxx1116filesystem_errorE`, this seemed like some compatibility issue with the ruby / library versions.

while i am able to use the library locally:
<img width="737" alt="image" src="https://github.com/ankane/fastText-ruby/assets/15105247/966344e5-759c-43b1-a13e-de480562a584">

Any help on how to fix this? 

Thanks!

**Comment by ankane** [comment]
Hi @sandeepm96, which Docker image are you using?

(if Buster, upgrading to Bullseye should fix it: https://github.com/ankane/AnomalyDetection.rb/issues/4)
